routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::redirect('/home', '/manage/dashboard');
Route::redirect('/manage', '/manage/dashboard');

Route::prefix('admin/dashboard')->group(function() {
	Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
	Route::post('/login', 'Auth\LoginController@login')->name('login.submit');
	// Route::get('/', 'AdminController@index')->name('dashboard');
	Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
    // Password reset routes
	Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
	Route::post('/password/reset', 'Auth\ResetPasswordController@reset');
	Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
});
Route::prefix('manage')->middleware('role:superadministrator|administrator|user')->group(function () {
	Route::resource('/users', 'UsersControllers');
//   Route::resource('/permissions', 'PermissionController', ['except' => 'destroy']);
//   Route::resource('/roles', 'RoleController', ['except' => 'destroy']);
});
Route::prefix('manage')->middleware('role:superadministrator|administrator|user')->group(function () {
	Route::get('/dashboard', 'HomeController@index')->name('dashboard');

//Tour management
	Route::resource('tour', 'TourController');
	Route::get('featured/tour','TourController@featuredTours')->name('tour.featured');
	Route::get('tour/{id}/publish','TourController@publish')->name('tour.publish');
	Route::get('tour/{id}/unpublish','TourController@unpublish')->name('tour.unpublish');
	Route::get('{id}/featured',  'TourController@setAsfeatured')->name('feature.tour');
	Route::get('{id}/removefeatured', 'TourController@removeAsfeatured')->name('remove.feature');

//Trash management
	Route::get('tour/trash', 'TourController@viewTrash')->name('show.trash');
	Route::get('{id}/move-to-trash', 'TourController@moveTotrash')->name('move.trash');
	Route::get('{id}/move-from-trash', 'TourController@removeFromtrash')->name('move.from-trash');
//Tour itinerary management
	Route::get('tour/{id}/itineraries', 'ItineraryController@create')->name('itinerary-create');
	Route::post('tour/create/itinerary-store', 'ItineraryController@save')->name('itinerary-store');
	Route::post('itinerary/itinerary-destroy/{itinerary}', 'ItineraryController@destroy')->name('itinerary-destroy');
	Route::post('itinerary-edit', 'ItineraryController@update')->name('itinerary-edit');

	Route::resource('departure','DepartureController');

//Tour attributes
	Route::resource('difficulty', 'DifficultyController');
	Route::resource('group', 'GroupController');
	Route::resource('accommodation', 'AccommodationController');
	Route::resource('meals', 'MealController');
	Route::resource('season', 'SeasonController');
	Route::resource('regions', 'RegionController');
	Route::resource('includes', 'IncludedController');
	Route::resource('excludes', 'ExcludedController');
	Route::resource('tour-category', 'TourCategoryController');

//Carousel management
	Route::resource('carousel', 'CarouselController');
	Route::get('carousel/{id}/publish', 'CarouselController@publish')->name('carousel.publish');
	Route::get('carousel/{id}/unpublish', 'CarouselController@unpublish')->name('carousel.unpublish');

//Media management
	Route::resource('media', 'MediaController');
	Route::get('media/delete-unwanted/{name?}', 'MediaController@clearUnwanted')->name('media.clearUnwanted');

//Page management
	Route::resource('pages','PageController');
	Route::get('page/{id}/publish','PageController@publish')->name('page.publish');
	Route::get('page/{id}/unpublish','PageController@unpublish')->name('page.unpublish');

//Site attributes
	Route::resource('announcement','AnnouncementController');
	Route::resource('partner', 'PartnerController');
	Route::resource('setting', 'SettingController');

	//Event controller
	Route::resource('/events','EventController');
	//Team Controller
	Route::resource('/team', 'TeamController');
	//Member Controller
	Route::resource('/position', 'MemberController');
	//Instagram Feeds
	Route::resource('/instagram', 'InstaController');
	//Blog Post Category
	Route::resource('/post-category', 'PostCategoryController');
	Route::resource('/blog-post', 'BlogPostController');
	Route::get('blog-post/{id}/publish','BlogPostController@publish')->name('blog-post.publish');
	Route::get('blog-post/{id}/unpublish','BlogPostController@unpublish')->name('blog-post.unpublish');
});

Route::name('frontend.')->group(function () {
	Route::get('/', 'NewController@getIndex');
	Route::get('/whats-on', 'NewController@getEvents')->name('whatsOn');
	Route::get('/who-we-are', 'NewController@getAbout')->name('about');
	Route::get('/travel-blog', 'NewController@getPosts')->name('posts');
	Route::get('/contact', 'NewController@getContact')->name('contact');

	Route::prefix('what-we-do')->group(function () {
		Route::get('/', 'NewController@getCategories')->name('weDo');
		Route::get('/{category}', 'NewController@byCategory')->name('byCategory');
	});

	Route::prefix('where-we-go')->group(function () {
		Route::get('/', 'NewController@getRegions')->name('where');
		Route::get('/{category}', 'NewController@byRegion')->name('byRegion');
	});

	Route::prefix('trip')->group(function () {
		Route::get('{slug}','NewController@tripDetail')->name('tripDetail');
		Route::post('{slug}/book','NewController@tripBook')->name('tripBook');
		Route::post('{slug}/complete','PostController@bookingComplete')->name('bookingComplete');
		Route::get('{slug}/thank-you','NewController@thankYou')->name('thankYou');
		Route::get('download/{slug}','NewController@downloadPDF')->name('download');
	});
	//Travel Style
	Route::prefix('travel-style')->group(function () {
		Route::get('{slug}','NewController@fetchByCategory')->name('fetchByCategory');
		Route::get('{category}/{region}','NewController@region2package')->name('region2package');
	});
	//Destinations
	Route::prefix('destination')->group(function () {
		Route::get('{slug}','NewController@fetchByregion')->name('fetchByRegion');
		Route::get('{destionation}/{category}','NewController@destination2package')->name('destionation2package');
	});
	
	//Post Requests
	Route::post('/contact','PostController@postContact')->name('postContact');
	Route::post('/quickEnquiry','PostController@quickEnquiry')->name('postEnquiry');
	Route::post('brochure-request','PostController@requestBroucher')->name('brochure');
	Route::post('refer-a-friend','PostController@referFriend')->name('referFriend');

	Route::prefix('ajax')->group(function () {
		Route::get('fetch-departures','NewController@ajaxsearchdeparture')->name('departure');
		// Route::post('brochure-request','PostController@requestBroucher')->name('brochure');
	});

	Route::get('/travel-blog','NewController@travelBlog')->name('travelBlog');
	Route::get('/travel-blog/{slug}','NewController@singlePost')->name('singlePost');

	Route::get('/sitemap', 'NewController@getSitemap')->name('sitemap');
	Route::get('/press', 'NewController@getPartner')->name('press');
		
});

Route::name('page.')->group(function () {
	Route::get('/{slug}','NewController@getPage')->name('getPage');
});

app/Meal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Meal extends Model
{
	public function tours()
	{
		return $this->hasMany('App\Tour');
	}
}

app/Tour.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Spatie\Feed\Feedable;
use Spatie\Feed\FeedItem;
class Tour extends Model implements Feedable
{
	use Sluggable;

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
    	return [
    		'slug' => [
    			'source' => 'title'
    		]
    	];
    }

    public function category()
    {
        return $this->belongsTo('App\TourCategory', 'category_id');
    }

    public function meal() //Works perfectly
    {
        return $this->belongsTo('App\Meal');
    }

    public function group() //Works perfectly
    {
        return $this->belongsTo('App\Group');
    }

    public function difficulty() //Works perfectly
    {
        return $this->belongsTo('App\Difficulty');
    }

    public function region()  //Works perfectly
    {
        return $this->belongsTo('App\Region');
    }

    public function accommodation() //Works perfectly
    {
        return $this->belongsTo('App\Accommodation');
    }
    public function includes()
    {
        return $this->belongsToMany('App\Included','includes_tour', 'tour_id', 'included_id')->orderBy('name', 'asc');
    }

    public function excludes()
    {
        return $this->belongsToMany('App\Excluded','excludes_tour', 'tour_id', 'excluded_id')->orderBy('name', 'asc');
    }

    public function image()
    {
        return $this->hasOne('App\FeaturedImage');
    }

    public function departure()
    {
        return $this->hasMany('App\Departure', 'tour_id');
    }

    public function itinerary()
    {
        return $this->hasMany('App\Itinerary', 'tour_id')->orderBy('id', 'asc');
    }

    public function slides()
    {
        return $this->hasMany('App\Slide', 'tour_id');
    }

    public function budgetIncludes()
    {
        return $this->belongsToMany('App\Included','includeds_btour', 'tour_id', 'included_id')->orderBy('name', 'asc');
    }

    public function budgetExcludes()
    {
        return $this->belongsToMany('App\Excluded','excludeds_btour', 'tour_id', 'excluded_id')->orderBy('name', 'asc');
    }

    public function toFeedItem()
    {
        return FeedItem::create()
            ->id($this->id)
            ->title($this->title)
            ->summary($this->overview)
            ->updated($this->updated_at)
            ->link($this->link)
            ->author('Crusade Himalaya');
    }

    public static function getFeedItems()
    {
        return static::all();
    }

    public function getLinkAttribute()
    {
        return route('events.show', $this);
    }    
}

app/Http/Controllers/MealController.php
<?php

namespace App\Http\Controllers;

use App\Meal;
use Session;
use Illuminate\Http\Request;

class MealController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $meals = Meal::all();
        return view('backend.tour.meal.index')->withMeals($meals);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(
            'name' => 'required|max:255'
        ));
        $meal = new Meal();
        $meal->name = $request->name;
        $meal->save();
        Session::flash('success', 'New item added sucessfully.');
        return redirect()->route('meals.index');        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Meal  $meal
     * @return \Illuminate\Http\Response
     */
    public function show(Meal $meal)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Meal  $meal
     * @return \Illuminate\Http\Response
     */
    public function edit(Meal $meal)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Meal  $meal
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:244',
        ]);
        $meal = Meal::find($request->id);
        $meal->name = $request->name;

        $meal->save();

        return response()->json($meal);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Meal  $meal
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $meal = Meal::findOrFail($id);
        $meal->delete();
        return response()->json($meal);
    }
}

resources/views/backend/tour/meal/index.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
    <div class="col-lg-8">
        <div class="table-responsive">
            <table id="datatable1" class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($meals as $meal)
                    <tr class="item{{$meal->id}}">
                        <td><h4>{{$loop->iteration}}</h4></td>
                        <td><h4>{{$meal->name}}</h4></td>
                        <td>
                            <button type="submit" class="btn ink-reaction btn-floating-action btn-sm btn-info " id="edit-modal" style="margin-right: 10px;"
                            data-id="{{$meal->id}}" data-name="{{$meal->name}}" data-toggle="modal"
                            data-target="#formModal">
                            <i class="fas fa-pencil-alt" aria-hidden="true"></i>
                        </button>
                        <button type="button" class="btn ink-reaction btn-floating-action btn-sm  btn-danger" data-id="{{$meal->id}}" data-toggle="modal"
                            data-target="#deleteModal" id="delete-modal">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div><!--end .table-responsive -->
</div><!--end .col -->
<div class="col-lg-4">
    <form class="form" method="POST" action="{{ route('meals.store') }}">
        @csrf
        <div class="card">
            <div class="card-head style-primary">
                <header>Create new category</header>
            </div>
            <div class="card-body floating-label">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <input type="text" class="form-control" id="name" name="name">
                            <label for="name">Name</label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-10 col-sm-offset-1">
                        <button type="submit" class="btn btn-block style-primary ink-reaction">Add</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
</div><!--end .row -->
<!-- BEGIN EDIT MODAL MARKUP -->
<div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-labelledby="formModalLabel"
aria-hidden="true">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="formModalLabel">Edit</h4>
        </div>
        <form class="form-horizontal" role="form">
            <div class="modal-body">
                <div class="form-group">
                    <input type="hidden" id="edit-id">
                    <div class="col-sm-3">
                        <label for="name" class="control-label">Name</label>
                    </div>
                    <div class="col-sm-9">
                        <input type="text" name="name" id="edit-name" class="form-control">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary save">Update</button>
            </div>
        </form>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!-- END EDIT MODAL MARKUP -->
<!-- BEGIN Delete MODAL MARKUP -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="formModalLabel"
aria-hidden="true">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="formModalLabel">Delete</h4>
        </div>
        <form class="form-horizontal" role="form">
            <div class="modal-body text-center">
                <input type="hidden" id="id-delete">
                <h4>Are you sure you want to delete ?</h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary delete">Delete</button>
            </div>
        </form>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!-- END Delete MODAL MARKUP -->
@stop
@section('scripts')
<script>
    $(document).ready(function () {
            //edit
            $(document).on('click', '#edit-modal', function () {
                $('#edit-id').val($(this).data('id'));
                $('#edit-name').val($(this).data('name'));
            });

            $('.modal-footer').on('click', '.save', function () {
                var id = $('#edit-id').val();
                $.ajax({
                    type: 'PUT',
                    url: '/manage/meals/' + id,
                    data: {
                        '_token': $('meta[name="csrf-token"]').attr('content'),
                        'id': $("#edit-id").val(),
                        'name': $('#edit-name').val()
                    },
                    success: function (data) {
                        $('#formModal').modal('hide');
                        toastr.success('Item update success!', 'Info Alert');
                        location.reload();
                    }

                });
            });
            //delete
            $(document).on('click', '#delete-modal', function () {
                $('#id-delete').val($(this).data('id'));
                var id = $('#id-delete').val();
            });

            $('.modal-footer').on('click', '.delete', function () {
                var id = $('#id-delete').val();
                $.ajax({
                    type: 'DELETE',
                    url: '/manage/meals/' + id,
                    data: {
                        '_token': $('meta[name="csrf-token"]').attr('content'),
                        'id': $("#id-delete").val()
                    },
                    success: function (data) {
                        $('#deleteModal').modal('hide');
                        toastr.success('Item deleted sucessfully!', 'Success Alert');
                        $('.item' + data['id']).remove();
                    }

                });
            });

        });
    </script>
    @stop