routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::redirect('/home', '/manage/dashboard');
Route::redirect('/manage', '/manage/dashboard');

Route::prefix('admin/dashboard')->group(function() {
	Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
	Route::post('/login', 'Auth\LoginController@login')->name('login.submit');
	// Route::get('/', 'AdminController@index')->name('dashboard');
	Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
    // Password reset routes
	Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
	Route::post('/password/reset', 'Auth\ResetPasswordController@reset');
	Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
});
Route::prefix('manage')->middleware('role:superadministrator|administrator|user')->group(function () {
	Route::resource('/users', 'UsersControllers');
//   Route::resource('/permissions', 'PermissionController', ['except' => 'destroy']);
//   Route::resource('/roles', 'RoleController', ['except' => 'destroy']);
});
Route::prefix('manage')->middleware('role:superadministrator|administrator|user')->group(function () {
	Route::get('/dashboard', 'HomeController@index')->name('dashboard');

//Tour management
	Route::resource('tour', 'TourController');
	Route::get('featured/tour','TourController@featuredTours')->name('tour.featured');
	Route::get('tour/{id}/publish','TourController@publish')->name('tour.publish');
	Route::get('tour/{id}/unpublish','TourController@unpublish')->name('tour.unpublish');
	Route::get('{id}/featured',  'TourController@setAsfeatured')->name('feature.tour');
	Route::get('{id}/removefeatured', 'TourController@removeAsfeatured')->name('remove.feature');

//Trash management
	Route::get('tour/trash', 'TourController@viewTrash')->name('show.trash');
	Route::get('{id}/move-to-trash', 'TourController@moveTotrash')->name('move.trash');
	Route::get('{id}/move-from-trash', 'TourController@removeFromtrash')->name('move.from-trash');
//Tour itinerary management
	Route::get('tour/{id}/itineraries', 'ItineraryController@create')->name('itinerary-create');
	Route::post('tour/create/itinerary-store', 'ItineraryController@save')->name('itinerary-store');
	Route::post('itinerary/itinerary-destroy/{itinerary}', 'ItineraryController@destroy')->name('itinerary-destroy');
	Route::post('itinerary-edit', 'ItineraryController@update')->name('itinerary-edit');

	Route::resource('departure','DepartureController');

//Tour attributes
	Route::resource('difficulty', 'DifficultyController');
	Route::resource('group', 'GroupController');
	Route::resource('accommodation', 'AccommodationController');
	Route::resource('meals', 'MealController');
	Route::resource('season', 'SeasonController');
	Route::resource('regions', 'RegionController');
	Route::resource('includes', 'IncludedController');
	Route::resource('excludes', 'ExcludedController');
	Route::resource('tour-category', 'TourCategoryController');

//Carousel management
	Route::resource('carousel', 'CarouselController');
	Route::get('carousel/{id}/publish', 'CarouselController@publish')->name('carousel.publish');
	Route::get('carousel/{id}/unpublish', 'CarouselController@unpublish')->name('carousel.unpublish');

//Media management
	Route::resource('media', 'MediaController');
	Route::get('media/delete-unwanted/{name?}', 'MediaController@clearUnwanted')->name('media.clearUnwanted');

//Page management
	Route::resource('pages','PageController');
	Route::get('page/{id}/publish','PageController@publish')->name('page.publish');
	Route::get('page/{id}/unpublish','PageController@unpublish')->name('page.unpublish');

//Site attributes
	Route::resource('announcement','AnnouncementController');
	Route::resource('partner', 'PartnerController');
	Route::resource('setting', 'SettingController');

	//Event controller
	Route::resource('/events','EventController');
	//Team Controller
	Route::resource('/team', 'TeamController');
	//Member Controller
	Route::resource('/position', 'MemberController');
	//Instagram Feeds
	Route::resource('/instagram', 'InstaController');
	//Blog Post Category
	Route::resource('/post-category', 'PostCategoryController');
	Route::resource('/blog-post', 'BlogPostController');
	Route::get('blog-post/{id}/publish','BlogPostController@publish')->name('blog-post.publish');
	Route::get('blog-post/{id}/unpublish','BlogPostController@unpublish')->name('blog-post.unpublish');
});

Route::name('frontend.')->group(function () {
	Route::get('/', 'NewController@getIndex');
	Route::get('/whats-on', 'NewController@getEvents')->name('whatsOn');
	Route::get('/who-we-are', 'NewController@getAbout')->name('about');
	Route::get('/travel-blog', 'NewController@getPosts')->name('posts');
	Route::get('/contact', 'NewController@getContact')->name('contact');

	Route::prefix('what-we-do')->group(function () {
		Route::get('/', 'NewController@getCategories')->name('weDo');
		Route::get('/{category}', 'NewController@byCategory')->name('byCategory');
	});

	Route::prefix('where-we-go')->group(function () {
		Route::get('/', 'NewController@getRegions')->name('where');
		Route::get('/{category}', 'NewController@byRegion')->name('byRegion');
	});

	Route::prefix('trip')->group(function () {
		Route::get('{slug}','NewController@tripDetail')->name('tripDetail');
		Route::post('{slug}/book','NewController@tripBook')->name('tripBook');
		Route::post('{slug}/complete','PostController@bookingComplete')->name('bookingComplete');
		Route::get('{slug}/thank-you','NewController@thankYou')->name('thankYou');
		Route::get('download/{slug}','NewController@downloadPDF')->name('download');
	});
	//Travel Style
	Route::prefix('travel-style')->group(function () {
		Route::get('{slug}','NewController@fetchByCategory')->name('fetchByCategory');
		Route::get('{category}/{region}','NewController@region2package')->name('region2package');
	});
	//Destinations
	Route::prefix('destination')->group(function () {
		Route::get('{slug}','NewController@fetchByregion')->name('fetchByRegion');
		Route::get('{destionation}/{category}','NewController@destination2package')->name('destionation2package');
	});
	
	//Post Requests
	Route::post('/contact','PostController@postContact')->name('postContact');
	Route::post('/quickEnquiry','PostController@quickEnquiry')->name('postEnquiry');
	Route::post('brochure-request','PostController@requestBroucher')->name('brochure');
	Route::post('refer-a-friend','PostController@referFriend')->name('referFriend');

	Route::prefix('ajax')->group(function () {
		Route::get('fetch-departures','NewController@ajaxsearchdeparture')->name('departure');
		// Route::post('brochure-request','PostController@requestBroucher')->name('brochure');
	});

	Route::get('/travel-blog','NewController@travelBlog')->name('travelBlog');
	Route::get('/travel-blog/{slug}','NewController@singlePost')->name('singlePost');

	Route::get('/sitemap', 'NewController@getSitemap')->name('sitemap');
	Route::get('/press', 'NewController@getPartner')->name('press');
		
});

Route::name('page.')->group(function () {
	Route::get('/{slug}','NewController@getPage')->name('getPage');
});

resources/views/backend/page/create.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
    <div class="col-lg-offset-1 col-md-10">
        {!! Form::open(['route' => 'pages.store', 'class'=>'form form-validate','files'=> true ]) !!}
        <div class="card">
            <div class="card-head style-primary">
                <header>Create new page</header>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group {{$errors->has('title') ? 'has-error' : ''}}">
                            {{ Form::text('title', Request::old('title'), ['class' => 'form-control', 'placeholder' => 'Enter title here', 'required']) }}
                            @if($errors->has('title'))
                            <span class="help-block">{{ $errors->first('title') }}</span>
                            @endif
                            {{ Form::label('title', 'Title ') }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group {{$errors->has('subheading') ? 'has-error' : ''}}">
                            {{ Form::text('subheading', Request::old('subheading'), ['class' => 'form-control', 'placeholder' => 'Enter subheading here', 'required']) }}
                            @if($errors->has('subheading'))
                            <span class="help-block">{{ $errors->first('subheading') }}</span>
                            @endif
                            {{ Form::label('subheading', 'Sub heading ') }}
                        </div>
                    </div>
                </div>                
                <div class="row">
                    <div class="col-md-2">
                        <div class="form-group  {{$errors->has('position') ? 'has-error' : ''}}">
                            <input type="text" class="form-control input-md m-b-sm" name="position">
                            <label for="position">Position</label>
                            @if ($errors->has('position'))
                            <span class="help-block">{{$errors->first('position')}}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group {{$errors->has('main') ? 'has-error' : ''}}">
                            <label class="col-sm-6 control-label">Main or Sub</label>
                            <div class="col-sm-6">
                                <label class="radio-inline radio-styled radio-success">
                                    <input type="radio" value="1" name="main" checked onclick="hidemenu()"><span>Main</span>
                                </label>
                                <label class="radio-inline radio-styled radio-info">
                                    <input type="radio" value="0" name="main" onclick="showmenu()"><span>Sub</span>
                                </label>
                            </div>
                            @if($errors->has('status'))
                            <span class="help-block">{{ $errors->first('main') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-5" id="parent">
                        <div class="form-group  {{$errors->has('parent_id') ? 'has-error' : ''}}">
                            <select class="form-control m-b-sm" name="parent_id" id="name">
                                @foreach($pages as $page)
                                <option value="{{$page->id}}">{{$page->title}}</option>
                                @endforeach
                            </select>
                            <label class="control-label">Parent Page</label>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <button type="button" class="btn btn-block ink-reaction btn-info" data-toggle="modal"
                            data-target="#myModal">
                            <i class="far fa-image"></i>  Banner Image
                        </button>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group {{$errors->has('status') ? 'has-error' : ''}}">
                        <label class="col-sm-6 control-label">Status</label>
                        <div class="col-sm-6">
                            <label class="radio-inline radio-styled radio-success">
                                <input type="radio" value="1" name="status" checked><span>Publish</span>
                            </label>
                            <label class="radio-inline radio-styled radio-warning">
                                <input type="radio" value="0" name="status"><span>Draft</span>
                            </label>
                        </div>
                        @if($errors->has('status'))
                        <span class="help-block">{{ $errors->first('status') }}</span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <textarea name="page_content"> </textarea>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group {{$errors->has('mtitle') ? 'has-error' : ''}}">
                        {{ Form::text('mtitle', null, ['class' => 'form-control', 'id'=>'mtitle']) }}
                        @if($errors->has('mtitle'))
                        <span class="help-block">{{ $errors->first('mtitle') }}</span>
                        @endif
                        {{ Form::label('mtitle', 'Meta Title ') }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12" id="desc">
                    <div class="form-group  {{$errors->has('description') ? 'has-error' : ''}}">
                      <textarea v-model="desc" class="form-control meta" maxlength="160" name="description"
                      id="description {{$errors->has('description')? 'inputError' : ''}}">
                  </textarea>
                  @if ($errors->has('description'))
                  <span class="help-block">{{$errors->first('description')}}</span>
                  @endif
                  <label for="textarea2">Description</label>
              </div>
              <em class="text-caption"><span>@{{ descRemaining }}</span> characters remaining.</em>
          </div>
      </div>
  </div><!--end .card body-->
  <div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Media Images</h4>
            </div>
            <div class="modal-body text-center">
                @if(!empty($images))
                <select class="image-picker show-html"
                name="banner">
                <option value=""></option>
                @foreach($images  as $image)

                <option data-img-src="{{asset($image->thumb)}}"
                    value="{{$image->id}}">
                </option>
                @endforeach
            </select>
            @else
            <h2>No images uploaded in media.</h2>
            @endif
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>

</div>
</div>
<div class="card-actionbar">
    <div class="card-actionbar-row">
        {{ Form::submit('Create', ['class' => 'btn btn-lg btn-flat btn-primary ink-reaction'] )}}
    </div>
</div>
{!! Form::close() !!}
</div><!--end .col -->
</div>
</div>
@endsection
@section('styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/image-picker/0.3.0/image-picker.min.css">
@stop
@section('scripts')
<script src="{{ asset('assets/backend/js/core/demo/DemoFormComponents.js') }}"></script>
<script src="{{ asset('assets/backend/js/libs/ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('assets/backend/js/libs/ckeditor/adapters/jquery.js') }}"></script>
<script src="{{ asset('assets/backend/js/core/demo/DemoFormEditors.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/image-picker/0.3.0/image-picker.min.js"></script>
<script>
    $("#parent").hide();
    document.getElementById("name").disabled = true;

    function showmenu() {
        document.getElementById('parent').style.display = 'block';
        document.getElementById("name").disabled = false;
    }

    function hidemenu() {
        document.getElementById('parent').style.display = 'none';
        document.getElementById("name").disabled = true;
    }
    CKEDITOR.replace('page_content', {
        height: 500
    });
    $(".image-picker").imagepicker();
</script>
@stop

resources/views/backend/page/index.blade.php
@extends('layouts.backend')
@section('styles')
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap.min.css">
@stop
@section('content')
<div class="row">
    <div class="col-md-10"></div>
    <div class="col-md-2">
        <a href="{{ route('pages.create') }}" class="btn ink-reaction btn-raised btn-lg btn-primary btn-block">Create</a>
    </div>
    <hr>
</div>
<section class="style-default-bright">
    <div class="row">
        <div class="col-lg-12">
            <div class="table-responsive">
                <table id="datatable1" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th class="sort-alpha">Title</th>
                            <th data-orderable="false">Position</th>
                            <th data-orderable="false">Banner</th>
                            <th data-orderable="false">Meta Title</th>
                            <th data-orderable="false">Meta Description</th>
                            <th class="sort-alpha">Status</th>
                            <th data-orderable="false">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($pages as $page)
                        <tr>
                            <th><a href="{{ route('pages.show',$page->id) }}">{{$page->title}}</a></th>

                            <th>
                                @if(!$page->main)
                                <span class="label label-primary f-s-12">{{ $page->parent->title }}</span> <i class="fa fa-arrow-circle-right"></i>
                                @endif
                                <span class="label label-primary f-s-12">{{ $page->position }}</span>
                            </th>

                            <th>
                                @if($page->banner !=='')
                                <i class="fas fa-check text-success"></i>
                                @else
                                <i class="fas fa-times text-success"></i>
                                @endif
                            </th>

                            <th>
                                @if($page->meta_title !=='')
                                <i class="fas fa-check text-success"></i>
                                @else
                                <i class="fas fa-times text-success"></i>
                                @endif
                            </th>

                            <th>
                                @if($page->description !=='')
                                <i class="fas fa-check text-success"></i>
                                @else
                                <i class="fas fa-times text-success"></i>
                                @endif
                            </th>

                            <th>
                                @if($page->status)
                                <span class="label label-success">Published</span>
                                @else
                                <span class="label label-warning">Unpublished</span>
                                @endif
                            </th>
                            
                            <th>
                                <a href="{{ route('pages.edit',$page->id)}}" class="btn btn-block btn-sm ink-reaction btn-info">
                                    <i class="fa fa-pencil" aria-hidden="true"></i> Edit
                                </a>
                                @if($page->published != 0)
                                <a href="{{ route('page.publish',$page->id)}}" class="btn btn-block btn-sm ink-reaction btn-success">
                                    <i class="fa fa-print" aria-hidden="true"></i> Publish
                                </a>
                                @else
                                <a href="{{ route('page.unpublish',$page->id)}}" class="btn btn-block btn-sm ink-reaction btn-warning">
                                    <i class="fa fa-print" aria-hidden="true"></i> Unpublish
                                </a>
                                @endif
                                {!!  Form::open( array('route'=>array('pages.destroy', $page->id),'method'=>'DELETE')) !!}
                                <button type="submit" class="btn btn-block btn-sm ink-reaction btn-danger form-delete">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i> Delete
                                </button>
                                {!! Form::close() !!}
                            </th>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div><!--end .table-responsive -->
        </div><!--end .col -->
    </div><!--end .row -->
</section>
@endsection
@section('scripts')
<script src="{{ asset('assets/backend/js/core/demo/DemoTableDynamic.js') }}"></script>
<script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap.min.js"></script>
@stop

resources/views/backend/page/show.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="card card-tiles style-default-light">

            <!-- BEGIN BLOG POST HEADER -->
            <div class="row">
                <div class="col-sm-9">
                    <div class="card-body style-default-dark">
                        <h2>{{ $page->title}}</h2>
                        <div class="text-default-light">
                            Status:
                            @if($page->published == 0)
                            Unpublished
                            @else
                            Published
                            @endif
                        </div>
                        <div class="text-default-light">
                            Position:
                            @if(!$page->main)
                            <span class="label label-info">{{$page->parent->name}}</span>  <i class="fa fa-arrow-circle-right"></i>
                            @endif
                            <span class="label label-primary f-s-12">{{ $page->position }}</span>
                        </div>
                    </div>
                </div><!--end .col -->
                <div class="col-sm-3">
                    <div class="card-body">
                        <a href="{{ route('pages.index') }}"
                        class="btn btn-block ink-reaction btn-success">Save</a>
                        <a href="{{ route('pages.edit',$page->id) }}"
                         class="btn btn-block ink-reaction btn-info">Edit</a>
                     </div>
                 </div><!--end .col -->
             </div><!--end .row -->
             <!-- END BLOG POST HEADER -->

             <div class="row">

                <!-- BEGIN BLOG POST TEXT -->
                <div class="col-md-9">
                    <article class="style-default-bright">
                        <div class="card-body">
                            <img src="{{asset($page->banner) }}" alt="" class="img-responsive">
                            <p class="lead">
                                {!! $page->page_content !!}
                            </p>
                        </div><!--end .card-body -->
                    </article>
                </div><!--end .col -->
                <!-- END BLOG POST TEXT -->
            </div><!--end .row -->
        </div><!--end .card -->
    </div><!--end .col -->
</div><!--end .row -->
@stop