routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::redirect('/home', '/manage/dashboard');
Route::redirect('/manage', '/manage/dashboard');

Route::prefix('admin/dashboard')->group(function() {
	Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
	Route::post('/login', 'Auth\LoginController@login')->name('login.submit');
	// Route::get('/', 'AdminController@index')->name('dashboard');
	Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
    // Password reset routes
	Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
	Route::post('/password/reset', 'Auth\ResetPasswordController@reset');
	Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
});
Route::prefix('manage')->middleware('role:superadministrator|administrator|user')->group(function () {
	Route::resource('/users', 'UsersControllers');
//   Route::resource('/permissions', 'PermissionController', ['except' => 'destroy']);
//   Route::resource('/roles', 'RoleController', ['except' => 'destroy']);
});
Route::prefix('manage')->middleware('role:superadministrator|administrator|user')->group(function () {
	Route::get('/dashboard', 'HomeController@index')->name('dashboard');

//Tour management
	Route::resource('tour', 'TourController');
	Route::get('featured/tour','TourController@featuredTours')->name('tour.featured');
	Route::get('tour/{id}/publish','TourController@publish')->name('tour.publish');
	Route::get('tour/{id}/unpublish','TourController@unpublish')->name('tour.unpublish');
	Route::get('{id}/featured',  'TourController@setAsfeatured')->name('feature.tour');
	Route::get('{id}/removefeatured', 'TourController@removeAsfeatured')->name('remove.feature');

//Trash management
	Route::get('tour/trash', 'TourController@viewTrash')->name('show.trash');
	Route::get('{id}/move-to-trash', 'TourController@moveTotrash')->name('move.trash');
	Route::get('{id}/move-from-trash', 'TourController@removeFromtrash')->name('move.from-trash');
//Tour itinerary management
	Route::get('tour/{id}/itineraries', 'ItineraryController@create')->name('itinerary-create');
	Route::post('tour/create/itinerary-store', 'ItineraryController@save')->name('itinerary-store');
	Route::post('itinerary/itinerary-destroy/{itinerary}', 'ItineraryController@destroy')->name('itinerary-destroy');
	Route::post('itinerary-edit', 'ItineraryController@update')->name('itinerary-edit');

	Route::resource('departure','DepartureController');

//Tour attributes
	Route::resource('difficulty', 'DifficultyController');
	Route::resource('group', 'GroupController');
	Route::resource('accommodation', 'AccommodationController');
	Route::resource('meals', 'MealController');
	Route::resource('season', 'SeasonController');
	Route::resource('regions', 'RegionController');
	Route::resource('includes', 'IncludedController');
	Route::resource('excludes', 'ExcludedController');
	Route::resource('tour-category', 'TourCategoryController');

//Carousel management
	Route::resource('carousel', 'CarouselController');
	Route::get('carousel/{id}/publish', 'CarouselController@publish')->name('carousel.publish');
	Route::get('carousel/{id}/unpublish', 'CarouselController@unpublish')->name('carousel.unpublish');

//Media management
	Route::resource('media', 'MediaController');
	Route::get('media/delete-unwanted/{name?}', 'MediaController@clearUnwanted')->name('media.clearUnwanted');

//Page management
	Route::resource('pages','PageController');
	Route::get('page/{id}/publish','PageController@publish')->name('page.publish');
	Route::get('page/{id}/unpublish','PageController@unpublish')->name('page.unpublish');

//Site attributes
	Route::resource('announcement','AnnouncementController');
	Route::resource('partner', 'PartnerController');
	Route::resource('setting', 'SettingController');

	//Event controller
	Route::resource('/events','EventController');
	//Team Controller
	Route::resource('/team', 'TeamController');
	//Member Controller
	Route::resource('/position', 'MemberController');
	//Instagram Feeds
	Route::resource('/instagram', 'InstaController');
	//Blog Post Category
	Route::resource('/post-category', 'PostCategoryController');
	Route::resource('/blog-post', 'BlogPostController');
	Route::get('blog-post/{id}/publish','BlogPostController@publish')->name('blog-post.publish');
	Route::get('blog-post/{id}/unpublish','BlogPostController@unpublish')->name('blog-post.unpublish');
});

Route::name('frontend.')->group(function () {
	Route::get('/', 'NewController@getIndex');
	Route::get('/whats-on', 'NewController@getEvents')->name('whatsOn');
	Route::get('/who-we-are', 'NewController@getAbout')->name('about');
	Route::get('/travel-blog', 'NewController@getPosts')->name('posts');
	Route::get('/contact', 'NewController@getContact')->name('contact');

	Route::prefix('what-we-do')->group(function () {
		Route::get('/', 'NewController@getCategories')->name('weDo');
		Route::get('/{category}', 'NewController@byCategory')->name('byCategory');
	});

	Route::prefix('where-we-go')->group(function () {
		Route::get('/', 'NewController@getRegions')->name('where');
		Route::get('/{category}', 'NewController@byRegion')->name('byRegion');
	});

	Route::prefix('trip')->group(function () {
		Route::get('{slug}','NewController@tripDetail')->name('tripDetail');
		Route::post('{slug}/book','NewController@tripBook')->name('tripBook');
		Route::post('{slug}/complete','PostController@bookingComplete')->name('bookingComplete');
		Route::get('{slug}/thank-you','NewController@thankYou')->name('thankYou');
		Route::get('download/{slug}','NewController@downloadPDF')->name('download');
	});
	//Travel Style
	Route::prefix('travel-style')->group(function () {
		Route::get('{slug}','NewController@fetchByCategory')->name('fetchByCategory');
		Route::get('{category}/{region}','NewController@region2package')->name('region2package');
	});
	//Destinations
	Route::prefix('destination')->group(function () {
		Route::get('{slug}','NewController@fetchByregion')->name('fetchByRegion');
		Route::get('{destionation}/{category}','NewController@destination2package')->name('destionation2package');
	});
	
	//Post Requests
	Route::post('/contact','PostController@postContact')->name('postContact');
	Route::post('/quickEnquiry','PostController@quickEnquiry')->name('postEnquiry');
	Route::post('brochure-request','PostController@requestBroucher')->name('brochure');
	Route::post('refer-a-friend','PostController@referFriend')->name('referFriend');

	Route::prefix('ajax')->group(function () {
		Route::get('fetch-departures','NewController@ajaxsearchdeparture')->name('departure');
		// Route::post('brochure-request','PostController@requestBroucher')->name('brochure');
	});

	Route::get('/travel-blog','NewController@travelBlog')->name('travelBlog');
	Route::get('/travel-blog/{slug}','NewController@singlePost')->name('singlePost');

	Route::get('/sitemap', 'NewController@getSitemap')->name('sitemap');
	Route::get('/press', 'NewController@getPartner')->name('press');
		
});

Route::name('page.')->group(function () {
	Route::get('/{slug}','NewController@getPage')->name('getPage');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UsersControllers.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Role;
use DB;
use Session;
use Hash;
use Input;
class UsersControllers extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('backend.user.index')->withUsers($users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/user/index.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
  <div class="col-md-10"></div>
  <div class="col-md-2">
    <a href="{{ route('users.create') }}"
    class="btn ink-reaction btn-raised btn-lg btn-primary btn-block">Create</a>
  </div>
  <hr>
</div>
<section class="style-default-bright">
  <div class="row">
    <div class="col-lg-12">
      <div class="table-responsive">
        <table id="datatable1" class="table table-striped table-hover">
          <thead>
            <tr>
              <th class="sort-alpha">Title</th>
              <th class="sort-numeric">Days</th>
              <th class="sort-alpha">Category</th>
              <th data-orderable="false">Meta Title</th>
              <th data-orderable="false">Meta Description</th>
              <th class="sort-alpha">Status</th>
              <th data-orderable="false">Action</th>
            </tr>
          </thead>
          <tbody>
            @foreach($tours as $tour)
            <tr>
              <th><a href="{{ route('tour.show', $tour->id) }}">{{$tour->title}}</a></th>
              <th>{{$tour->days}}</th>
              <th>{{$tour->category->name}}</th>
              <th>
                @if($tour->mtitle)
                <i class="fas fa-check text-success"></i>
                @else
                <i class="fas fa-times text-danger"></i>
                @endif
              </th>
              <th>
                @if($tour->description)
                <i class="fas fa-check text-success"></i>
                @else
                <i class="fas fa-times text-danger"></i>
                @endif
              </th>
              <th>
                @if($tour->status)
                <span class="label label-success">Published</span>
                @else
                <span class="label label-warning">Unpublished</span>
                @endif
              </th>
              <th class="action-column">
                <a href="{{ route('tour.edit',$tour->id)}}"
                 class="btn btn-block btn-sm ink-reaction btn-info">
                 <i class="fas fa-pencil-alt" aria-hidden="true"></i> Edit
               </a>
               <a href="{{ route('itinerary-create',$tour->id)}}" class="btn btn-block ink-reaction btn-success btn-sm">
                <i class="fa fa-list-ol" aria-hidden="true"></i> Itinerary
              </a>
              @if(!$tour->status)
              <a href="{{ route('tour.publish',$tour->id)}}"
               class="btn btn-block btn-sm ink-reaction btn-success">
               <i class="fa fa-print" aria-hidden="true"></i> Publish
             </a>
             @else
             <a href="{{ route('tour.unpublish',$tour->id)}}"
               class="btn btn-block btn-sm ink-reaction btn-warning">
               <i class="fa fa-print" aria-hidden="true"></i> Unpublish
             </a>
             @endif

             @if(!$tour->featured )
             <a href="{{ route('feature.tour',$tour->id)}}"
               class="btn btn-block btn-sm ink-reaction btn-accent">
               <i class="fa fa-star" aria-hidden="true"></i> Set as Featured
             </a>
             @else
             <a href="{{ route('remove.feature',$tour->id)}}"
               class="btn btn-block btn-sm ink-reaction btn-warning">
               <i class="fa fa-star" aria-hidden="true"></i> Remove as Featured
             </a>
             @endif
             {!!  Form::open( array('route'=>array('tour.destroy', $tour->id),'method'=>'DELETE')) !!}
             <button type="submit" class="btn btn-block btn-sm ink-reaction btn-danger form-delete">
              <i class="fas fa-trash-alt" aria-hidden="true"></i> Delete
            </button>
            {!! Form::close() !!}
          </th>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div><!--end .table-responsive -->
</div><!--end .col -->
</div><!--end .row -->
</section>
@endsection
@section('styles')
{{-- <link type="text/css" rel="stylesheet" --}}
{{--           href="{{ asset('assets/backend/css/libs/DataTables/jquery.dataTables.css') }}"/>
    <link type="text/css" rel="stylesheet"
          href="{{ asset('assets/backend/css/libs/DataTables/extensions/dataTables.colVis.css') }}"/>
    <link type="text/css" rel="stylesheet"
    href="{{ asset('assets/backend/css/libs/DataTables/extensions/dataTables.tableTools.css') }}"/> --}}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap.min.css">
    <style>
    .action-column .btn{
      margin-top: 8px !important;
    }
  </style>
  @stop
  @section('scripts')
  <script src="{{ asset('assets/backend/js/core/demo/DemoTableDynamic.js') }}"></script>
  <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap.min.js"></script>
  @stop